name: AutoGroup-Donations
version: 1.0
description: Bukkit plugin to automatically group users based on donation amounts.
author: md_5
website: https://github.com/md-5/AutoGroup-Donations

main: com.md_5.autogroup.donations.AutoGroup

commands:
  donate:
    description: Verify a donation using a Paypal transaction id
    aliases: don
    permission: autogroup.donate

permissions:
    autogroup.donate:
        description: Allows use of the donate command
        default: true